import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Til (UZ / RU). `tr('Saqlash')` — UZ matnni kalit sifatida ishlatadi,
/// rus tilida lug'atdan tarjimani qaytaradi, topilmasa UZ matnni qaytaradi.
class Lang extends ChangeNotifier {
  Lang._();
  static final Lang instance = Lang._();

  bool _isRu = false; // boshlang'ich: o'zbekcha
  bool get isRu => _isRu;

  Future<void> load() async {
    try {
      final p = await SharedPreferences.getInstance();
      _isRu = p.getBool('app_ru') ?? false;
      notifyListeners();
    } catch (_) {}
  }

  Future<void> toggle() async {
    _isRu = !_isRu;
    notifyListeners();
    try {
      final p = await SharedPreferences.getInstance();
      await p.setBool('app_ru', _isRu);
    } catch (_) {}
  }

  String t(String uz) {
    if (!_isRu) return uz;
    return _ru[uz] ?? uz;
  }
}

/// Qisqa global yordamchi: tr('Saqlash')
String tr(String uz) => Lang.instance.t(uz);

/// O'zbekcha -> Ruscha lug'at. Yangi matn qo'shilganda shu yerga qo'shing.
const Map<String, String> _ru = {
  // ── Navigatsiya ──
  'Bosh sahifa': 'Главная',
  'Xodimlar': 'Сотрудники',
  'Menyu': 'Меню',
  'Zakazlar': 'Заказы',
  'Harajatlar': 'Расходы',
  'Hisobot': 'Отчёт',
  'Inventarizatsiya': 'Инвентаризация',
  'Stollar': 'Столы',
  'Profil': 'Профиль',

  // ── Umumiy tugmalar / so'zlar ──
  'Saqlash': 'Сохранить',
  'Bekor': 'Отмена',
  'O\'chirish': 'Удалить',
  'Qo\'shish': 'Добавить',
  'Tahrirlash': 'Редактировать',
  'Yopish': 'Закрыть',
  'Ha': 'Да',
  'Yo\'q': 'Нет',
  'Ha, tugatildi': 'Да, завершено',
  'Ha, yoqish': 'Да, включить',
  'Ha, o\'chir': 'Да, удалить',
  'Ha, bekor qil': 'Да, отменить',
  'tayyor (zakaz qilsa bo\'ladi)': 'готово (можно заказать)',
  'STOP (tayyor emas)': 'СТОП (не готово)',
  'hozir tayyor emas (stop-list)': 'сейчас не готово (стоп-лист)',
  'Bo\'lim(lar) — chek shu sexlardan chiqadi': 'Отдел(ы) — чек выходит из этих цехов',
  'Taomni bekor qilish': 'Отменить блюдо',
  'shu taomni zakazdan o\'chirasizmi?': 'удалить это блюдо из заказа?',
  'Zakazni o\'chirish': 'Удалить заказ',
  'zakazni o\'chirasizmi? Savdo va kassadan ham ayriladi, sklad qaytariladi.': 'удалить заказ? Сумма вычтется из продаж и кассы, склад вернётся.',
  'zakazni butunlay o\'chirasizmi?': 'удалить заказ полностью?',
  'Kirish': 'Вход',
  'Chiqish': 'Выход',
  'Tizimga kirish': 'Вход в систему',
  'Yangilash': 'Обновить',
  'Tasdiqlash': 'Подтвердить',
  'Qidirish': 'Поиск',

  // ── Login ──
  'Telefon raqam': 'Номер телефона',
  'Parol': 'Пароль',
  'Yangi parol (ixtiyoriy)': 'Новый пароль (необязательно)',
  'Parol bilan kirish': 'Войти по паролю',
  'Kirish uchun bosing': 'Нажмите для входа',

  // ── Stollar / zakaz ──
  'Stol': 'Стол',
  'Bo\'sh': 'Свободен',
  'Band': 'Занят',
  'kishi': 'чел.',
  'Ofitsant': 'Официант',
  'Tugallanmagan': 'Незавершённые',
  'Tugallangan': 'Завершённые',
  'Tugatish (To\'landi)': 'Завершить (Оплачено)',
  '✓ Tugatish (To\'landi)': '✓ Завершить (Оплачено)',
  'Zakazni tugatish': 'Завершить заказ',
  'Pul olindi va zakaz tugallanadimi?': 'Деньги получены, завершить заказ?',
  'Zakaz yuborildi!': 'Заказ отправлен!',
  'Tugallanmagan zakaz yo\'q': 'Нет незавершённых заказов',
  'Tugallangan zakaz yo\'q': 'Нет завершённых заказов',
  'taom': 'блюд',
  'ta zakaz': 'заказов',
  'ta': 'шт',
  'bo\'sh': 'свободно',
  'Noma\'lum': 'Неизвестно',

  // ── Menyu / mahsulot ──
  'Kategoriyalar': 'Категории',
  'Taomlar': 'Блюда',
  'Sklad': 'Склад',
  'Taom qo\'shish': 'Добавить блюдо',
  'Taomni tahrirlash': 'Редактировать блюдо',
  'Taom nomi': 'Название блюда',
  'Narxi (so\'m)': 'Цена (сом)',
  'Kategoriya': 'Категория',
  'Bo\'lim (printer)': 'Отдел (принтер)',
  'Rasm tanlash': 'Выбрать фото',
  'Kategoriya nomi': 'Название категории',

  // ── Xodimlar ──
  'Xodim qo\'shish': 'Добавить сотрудника',
  'Xodimni tahrirlash': 'Редактировать сотрудника',
  'Ism familiya': 'Имя фамилия',
  'Lavozim': 'Должность',
  'Yangi lavozim': 'Новая должность',
  'Yangi lavozim...': 'Новая должность...',
  'Maosh turi': 'Тип зарплаты',
  'Maosh miqdori (so\'m)': 'Размер зарплаты (сом)',
  'Foiz miqdori (%)': 'Процент (%)',
  'Ish boshlanishi': 'Начало работы',
  'Ish tugashi': 'Конец работы',
  'Kechikish jarimasi (so\'m / daqiqa)': 'Штраф за опоздание (сом / мин)',
  'Face ID raqami': 'Номер Face ID',
  'Admin': 'Администратор',
  'Oshpaz': 'Повар',
  'Kassir': 'Кассир',
  'Sanitarka': 'Уборщица',
  'Xodimlar yo\'q': 'Нет сотрудников',

  // ── Harajatlar ──
  'Harajat qo\'shish': 'Добавить расход',
  'Harajat': 'Расход',
  'Jami harajat': 'Всего расходов',
  'Tur': 'Тип',
  'Nomi': 'Название',
  'Summa (сом)': 'Сумма (сом)',
  'Miqdor (ixtiyoriy)': 'Количество (необязательно)',
  'O\'lchov (kg/dona)': 'Ед. (кг/шт)',
  'Yangi tur': 'Новый тип',
  'Yangi tur...': 'Новый тип...',
  'Yangi harajat turi': 'Новый тип расхода',
  'Harajat yo\'q': 'Нет расходов',
  'Tur bo\'yicha taqsimot': 'Распределение по типам',
  'Soni': 'Кол-во',
  'Eng katta tur': 'Наибольший тип',

  // ── Bosh sahifa (dashboard) ──
  'Bugun': 'Сегодня',
  'Hafta': 'Неделя',
  'Oy': 'Месяц',
  'Savdo': 'Продажи',
  'Sof foyda': 'Чистая прибыль',
  'O\'rtacha chek': 'Средний чек',
  'Band stollar': 'Занятые столы',
  'Ishda xodim': 'На смене',
  'Kam qolgan sklad': 'Мало на складе',
  'Oxirgi 7 kun savdosi (сом)': 'Продажи за 7 дней (сом)',
  'Eng gavjum soatlar (сом)': 'Пиковые часы (сом)',
  'Bo\'lim bo\'yicha savdo (сом)': 'Продажи по отделам (сом)',
  'Eng ko\'p sotilgan TOP-5': 'ТОП-5 продаж',
  'Ofitsantlar reytingi': 'Рейтинг официантов',
  'Ma\'lumot yo\'q': 'Нет данных',

  // ── Printerlar / bo'limlar ──
  'Bo\'limlar / Printerlar': 'Отделы / Принтеры',
  'Bo\'lim nomi': 'Название отдела',
  'Printer ulanishi': 'Подключение принтера',
  'Tarmoq (IP)': 'Сеть (IP)',
  'USB printer': 'USB принтер',
  'Yo\'q (faylga)': 'Нет (в файл)',

  // ── Tema ──
  'Yorug\' / Qorong\'i': 'Светлая / Тёмная',

  // ── Login (qo'shimcha) ──
  'Sultan Restoran': 'Sultan Restoran',
  'Face ID / Fingerprint': 'Face ID / Отпечаток',
  'Keyingi safar Face ID yoki barmoq izi bilan kirishni xohlaysizmi?':
      'Хотите в следующий раз входить по Face ID или отпечатку?',
  'Sultan Restoranga kirish uchun tasdiqlang': 'Подтвердите вход в Sultan Restoran',

  // ── Ofitsant oynasi ──
  'Jami:': 'Итого:',
  'Taomlar:': 'Блюда:',
  'Zakaz berish': 'Оформить заказ',
  'Zakaz tasdiqlash': 'Подтверждение заказа',
  'Yuborish': 'Отправить',
  'Tema': 'Тема',
  'Test chek chiqarish': 'Тест печати',
  'Printerni sozlash': 'Настройка принтера',
  'Printerni tanlang': 'Выберите принтер',
  'Printer': 'Принтер',
  'Avval stol tanlang': 'Сначала выберите стол',
  'Zakaz berish uchun stollardan birini tanlang': 'Выберите стол для заказа',
  'Xonalar topilmadi': 'Залы не найдены',
  'Til': 'Язык',
  'Stollarga o\'tish': 'К столам',
  'Menyu bo\'sh': 'Меню пусто',
  'Bu xonada stol yo\'q': 'В этом зале нет столов',
  'Sozlamalar': 'Настройки',
  'Qorong\'u': 'Тёмная',
  'Yorug\'': 'Светлая',
  'Ilova haqida': 'О приложении',
  'Versiya': 'Версия',
  'Ishlab chiqaruvchi': 'Разработчик',
  'Foydalanuvchi': 'Пользователь',
  'Administrator': 'Администратор',
  'Tozalovchi': 'Уборщица',
  'Printerni sinash uchun namuna chek': 'Пробный чек для проверки принтера',
  'Tanlanmagan — bosing va tanlang': 'Не выбран — нажмите и выберите',
  'Izoh (ixtiyoriy)': 'Примечание (необязательно)',
  'Izoh': 'Примечание',
  'Printer topilmadi (tizimda o\'rnatilgan printer yo\'q)': 'Принтер не найден (в системе нет установленного принтера)',
  'Test chek printerga yuborildi': 'Пробный чек отправлен на принтер',
  'Printer tanlandi:': 'Принтер выбран:',
  'tanlandi. Taom qo\'shing.': 'выбран. Добавьте блюда.',

  // ── Admin: Menyu / Sklad ──
  'Mahsulot nomi': 'Название продукта',
  'Sklad nomi': 'Название склада',
  'Yangi sklad': 'Новый склад',
  'Yakunlash': 'Завершить',
  'Birlik': 'Ед.',
  'Narxi': 'Цена',
  'Retsept': 'Рецепт',
  'Retseptlarda ishlatiladi': 'Используется в рецептах',
  'Retseptdan biriktirish': 'Привязать из рецепта',
  'Qabul qilish': 'Приход',
  'Sotuvga chiqarish': 'Выставить на продажу',
  'Sotish narxi (so\'m)': 'Цена продажи (сом)',
  'Oshxona uchun ingredient': 'Ингредиент для кухни',
  'Tannarx hisoblanmoqda...': 'Себестоимость считается...',
  'Taom nomini qidiring...': 'Поиск блюда...',
  'Taom nomi qismi (masalan: сомса)': 'Часть названия (напр: сомса)',
  'Rasmni o\'zgartirish uchun bosing (ixtiyoriy)': 'Нажмите чтобы изменить фото (необязательно)',
  '＋ Yangi lavozim...': '＋ Новая должность...',
  '＋ Yangi tur...': '＋ Новый тип...',

  // ── Admin: Floor-plan / Stollar ──
  'Xona yaratish': 'Создать зал',
  'Xona nomi': 'Название зала',
  'Stol qo\'shish': 'Добавить стол',
  'Stolni tahrirlash': 'Редактировать стол',
  'Nomini tahrirlash': 'Редактировать название',
  'Ochish (stollar)': 'Открыть (столы)',
  'Suring • uzoq bosing': 'Тащите • долгое нажатие',
  'Yaratish': 'Создать',
  'Bino rejasi — xonani suring yoki ustiga bosing': 'План здания — тащите зал или нажмите',

  // ── Admin: Harajat / hisobot ──
  'Tur nomi (masalan: Reklama)': 'Название типа (напр: Реклама)',
  'Turni tanlang!': 'Выберите тип!',
  'Nom va summani kiriting!': 'Введите название и сумму!',
  'Xulosa': 'Итог',
  'Zarar': 'Убыток',
  'Ortiqcha': 'Излишек',
  'Ortiqchalar': 'Излишки',
  'PDF hisobot': 'PDF отчёт',
  'Ishchilar davomati': 'Посещаемость',
  'Kelganlar': 'Пришли',
  'Kelmaganlar': 'Не пришли',
  'Jami jarima': 'Всего штраф',
  'Keldi': 'Пришёл',
  'Ketdi': 'Ушёл',
  'Kelmadi': 'Не пришёл',

  // ── Admin: umumiy ──
  'Idishlar': 'Посуда',
  'Idishlar ro\'yxati': 'Список посуды',
  'Printer topilmadi. USB printerni ulab, ilovani qayta oching.':
      'Принтер не найден. Подключите USB и перезапустите.',

  // ── Umumiy xabarlar ──
  'Xato': 'Ошибка',
  'Diqqat': 'Внимание',
  'Tasdiqlaysizmi?': 'Подтверждаете?',
  'Avval sklad tanlang!': 'Сначала выберите склад!',

  // ── Admin: i18n to'ldirish (auto) ──
  'Boshqa': 'Другое',
  'Du': 'Пн',
  'Se': 'Вт',
  'Ch': 'Ср',
  'Pa': 'Чт',
  'Ju': 'Пт',
  'Sh': 'Сб',
  'Ya': 'Вс',
  'Tannarx': 'Себестоимость',
  'Foyda': 'Прибыль',
  'jarima': 'штраф',
  'daq': 'мин',
  'dona': 'шт',
  'ortiqcha': 'излишек',
  'so\'m': 'сом',
  'Kirim': 'Приход',
  'Nomi (masalan: Mol go\'shti)': 'Название (напр: Говядина)',
  'o\'chirilsinmi?': 'удалить?',
  'Nomini o\'zgartirish': 'Изменить название',
  'Skladni o\'chirish': 'Удалить склад',
  'skladini o\'chirilsinmi?': 'склад удалить?',
  'Bajarildi': 'Выполнено',
  'Kategoriya tahrirlash': 'Редактировать категорию',
  'kategoriyasini o\'chirishni tasdiqlaysizmi?\nFaqat bo\'sh kategoriyalarni o\'chirish mumkin.': 'категорию удалить?\nМожно удалять только пустые категории.',
  'Kategoriyada faol taomlar bor!': 'В категории есть активные блюда!',
  'taomini o\'chirishni tasdiqlaysizmi?': 'блюдо удалить?',
  'Kategoriya qo\'shish': 'Добавить категорию',
  'retsept': 'рецепт',
  'Masaliqlar kiritilmagan': 'Ингредиенты не добавлены',
  'Masaliq qo\'shish': 'Добавить ингредиент',
  'Masaliq nomi': 'Название ингредиента',
  'Miqdori': 'Количество',
  'Sklad — mahsulot qo\'shish': 'Склад — добавить продукт',
  'mahsulot qo\'shish': 'добавить продукт',
  'O\'lchov birligi': 'Единица измерения',
  'Boshlang\'ich miqdor': 'Начальное количество',
  'Kirish narxi (so\'m)': 'Цена прихода (сом)',
  'Minimum miqdor (ogohlantirish)': 'Минимальное количество (предупреждение)',
  '* Bu miqdordan kam bo\'lsa xabar beriladi': '* Если меньше этого количества, будет уведомление',
  'retseptdan biriktirish': 'привязать из рецепта',
  'Tanlangan taomlar retseptidagi ingredientlar shu skladga biriktiriladi. Kamida bittasini to\'ldiring.': 'Ингредиенты из рецептов выбранных блюд будут привязаны к этому складу. Заполните хотя бы одно поле.',
  'Kategoriya nomi (masalan: Шашлык)': 'Название категории (напр: Шашлык)',
  'ta ingredient biriktirildi': 'ингредиентов привязано',
  'Biriktirish': 'Привязать',
  'Mahsulot nomini qidiring...': 'Поиск названия продукта...',
  'Sklad bo\'sh': 'Склад пуст',
  'Natija topilmadi': 'Ничего не найдено',
  'Sotish': 'Продажа',
  'Narx': 'Цена',
  'Retseptlar': 'Рецепты',
  'Masaliq': 'Ингредиент',
  'Masaliqni tahrirlash': 'Изменить ингредиент',
  'Brutto': 'Брутто',
  'Brutto (xom)': 'Брутто (вес)',
  'Chiqish %': 'Выход %',
  'Netto': 'Нетто',
  'JAMI': 'ИТОГО',
  'Narx (1 birlik)': 'Цена (1 ед.)',
  'Sklad (qaysi sex)': 'Склад (какой цех)',
  'Chek chiqarilmoqda...': 'Чек печатается...',
  'Bugunga': 'На сегодня',
  'Kassa ochilishi': 'Открытие кассы',
  'Kassani ochish': 'Открыть кассу',
  'Kassa qancha naqd pul bilan ochilyapti?': 'С какой суммой наличных открывается касса?',
  'Boshlang\'ich summa': 'Начальная сумма',
  'Ochish': 'Открыть',
  'Kassa ochildi': 'Касса открыта',
  '🧾 Hisob (Счёт)': '🧾 Счёт',
  'To\'liq naqd': 'Полностью наличные',
  'To\'liq karta': 'Полностью карта',
  'Tip yo\'q': 'Нет типов',
  'Masaliqlar kiritilmagan. "+" bilan qo\'shing.': 'Ингредиенты не добавлены. Добавьте через "+".',
  'Tipni oching -> taomni bosing -> masaliqlar (brutto, chiqish%, narx). Netto va tannarx avtomatik hisoblanadi.': 'Откройте тип -> нажмите блюдо -> ингредиенты (брутто, выход%, цена). Нетто и себестоимость считаются автоматически.',
  'KAM QOLDI!': 'МАЛО ОСТАЛОСЬ!',
  '+ Kirim': '+ Приход',
  'O\'chirishni tasdiqlang': 'Подтвердите удаление',
  'mahsulotini o\'chirmoqchimisiz?': 'хотите удалить продукт?',
  'Faqat ombor bo\'sh (0) bo\'lsa o\'chiriladi.': 'Удаляется только если склад пуст (0).',
  'O\'chirildi!': 'Удалено!',
  'kirim': 'приход',
  'Kirish narxi': 'Цена прихода',
  // --- Sklad mahsulotini tahrirlash + sabab ---
  'Mahsulotni tahrirlash': 'Изменить продукт',
  'Sabab (majburiy)': 'Причина (обязательно)',
  'Nima uchun o\'zgartiryapsiz?': 'Почему вы вносите изменение?',
  'Sabab yozish shart!': 'Обязательно напишите причину!',
  'Minimal miqdor': 'Мин. количество',
  'Qoldiq (tuzatish)': 'Остаток (коррекция)',
  'Kirim narxi': 'Цена прихода',
  'Sotish narxi': 'Цена продажи',
  'O\'zgartirildi!': 'Изменено!',
  'Hech narsa o\'zgarmadi': 'Ничего не изменилось',
  'O\'zgarishlar tarixi': 'История изменений',
  'Tarix': 'История',
  'Tarix bo\'sh': 'История пуста',
  'Bu mahsulot qanday ishlatiladi?': 'Как используется этот продукт?',
  'To\'g\'ridan mijozga sotiladi': 'Продаётся напрямую клиенту',
  'Menyu kategoriyasi': 'Категория меню',
  'Qabul qilindi! Jami:': 'Принято! Итого:',
  'Kam qoldi': 'Мало осталось',
  'Kategoriyalar yo\'q': 'Нет категорий',
  'Taomlar yo\'q': 'Нет блюд',
  'Oylik (belgilangan summa)': 'Месячная (фиксированная сумма)',
  'Kunlik': 'Дневная',
  'Jami tushum': 'Общий доход',
  'Jami tushumdan foiz': 'Процент от общего дохода',
  'Jami tushumdan foiz (%)': 'Процент от общего дохода (%)',
  'Soatlik': 'Почасовая',
  'Savdodan foiz (%)': 'Процент с продаж (%)',
  'Lavozim nomi (masalan: elektrik)': 'Название должности (напр: электрик)',
  '* Face ID — xodimning kirish/chiqish kartasi raqami': '* Face ID — номер карты входа/выхода сотрудника',
  '* Masalan: 10 — har 100 000 so\'m savdodan 10 000 so\'m oladi': '* Например: 10 — с каждых 100 000 сом продаж получает 10 000 сом',
  '* 1 daqiqa kech qolsa shu summa jarima yoziladi': '* За каждую минуту опоздания начисляется этот штраф',
  'Ism, telefon va parolni to\'ldiring!': 'Заполните имя, телефон и пароль!',
  'Lavozimni tanlang!': 'Выберите должность!',
  '* Bo\'sh qolsa parol o\'zgarmaydi': '* Если оставить пустым, пароль не изменится',
  'Oylik': 'Месячная',
  'Foiz': 'Процент',
  'Bo\'limni tahrirlash': 'Редактировать отдел',
  'Yangi bo\'lim': 'Новый отдел',
  'Bo\'lim nomi (masalan: Oshxona)': 'Название отдела (напр: Кухня)',
  'Printer IP (masalan: 192.168.1.50)': 'IP принтера (напр: 192.168.1.50)',
  'Port (odatda 9100)': 'Порт (обычно 9100)',
  'Chek faylga yoziladi (backend/tickets) — printer kelguncha sinov uchun.': 'Чек записывается в файл (backend/tickets) — для теста, пока нет принтера.',
  'bo\'limini o\'chirasizmi?': 'отдел удалить?',
  'Har bo\'limga printer IP belgilang. Taom shu bo\'lim printeriga chiqadi. IP bo\'sh bo\'lsa, chek faylga yoziladi (printer kelguncha sinov uchun).': 'Укажите IP принтера для каждого отдела. Блюдо печатается на принтере этого отдела. Если IP пуст, чек записывается в файл (для теста, пока нет принтера).',
  'Bo\'lim yo\'q': 'Нет отделов',
  'Printer belgilanmagan (faylga)': 'Принтер не указан (в файл)',
  'Ish': 'Работа',
  'hali ishda': 'ещё на работе',
  'daq kech': 'мин опоздание',
  'Inventarizatsiya yo\'q': 'Нет инвентаризаций',
  'Yakunlangan': 'Завершена',
  'Ochiq': 'Открыта',
  'Idishni tahrirlash': 'Редактировать посуду',
  'Yangi idish': 'Новая посуда',
  'Nomi (masalan: Piola)': 'Название (напр: Пиала)',
  'O\'lchov (dona/komplekt)': 'Ед. (шт/комплект)',
  'Mavjud soni': 'Имеющееся количество',
  'Bittasining narxi (so\'m)': 'Цена за единицу (сом)',
  'Idish nomini kiriting!': 'Введите название посуды!',
  'idishini ro\'yxatdan o\'chirasizmi?': 'удалить из списка посуды?',
  'Idishlar yo\'q. "+" bilan qo\'shing.': 'Посуды нет. Добавьте через "+".',
  'Inventarizatsiyani yakunlashni tasdiqlaysizmi?\nSklad yangilanadi.': 'Подтверждаете завершение инвентаризации?\nСклад будет обновлён.',
  'Inventarizatsiya hisoboti': 'Отчёт по инвентаризации',
  'O\'lchov': 'Ед. изм.',
  'Kutilgan': 'Ожидалось',
  'Haqiqiy': 'Фактически',
  'Farq': 'Разница',
  'Kamomadlar': 'Недостачи',
  'Kamomad': 'Недостача',
  'Kamomad (zarar):': 'Недостача (убыток):',
  'Ortiqcha (qiymati):': 'Излишек (стоимость):',
  'Sof zarar:': 'Чистый убыток:',
  'Sof natija:': 'Чистый результат:',
  'PDF saqlandi': 'PDF сохранён',
  'Umumiy hisobot': 'Общий отчёт',
  'kamomad': 'недостача',
  'Jami zarar': 'Всего убыток',
  'Xona saqlanmadi': 'Зал не сохранён',
  'Xona nomi / raqami': 'Название / номер зала',
  'Xona yaratilmadi': 'Зал не создан',
  'Xonani o\'chirish': 'Удалить зал',
  'xonasi va undagi BARCHA stollar o\'chiriladi. Davom etasizmi?': 'зал и ВСЕ столы в нём будут удалены. Продолжить?',
  'Xona o\'chmadi': 'Зал не удалён',
  'Saqlanmadi': 'Не сохранено',
  'Stol saqlanmadi': 'Стол не сохранён',
  'Xona o\'lchami saqlanmadi': 'Размер зала не сохранён',
  'O\'lcham saqlanmadi': 'Размер не сохранён',
  'Stol raqami': 'Номер стола',
  'Necha kishilik': 'На сколько человек',
  'Stol qo\'shilmadi': 'Стол не добавлен',
  'Stol o\'chmadi': 'Стол не удалён',
  'O\'lcham': 'Размер',
  'Tahrirlash (raqam / o\'rindiq)': 'Редактировать (номер / места)',
  'stol': 'стол',
  'Stol qo\'shing': 'Добавьте стол',

  // ── Ish haqi (payroll) ──
  'Ish haqi': 'Зарплата',
  'Hisoblangan': 'Начислено',
  'To\'lanadigan': 'К выплате',
  'Belgilangan oylik': 'Фиксированный оклад',
  'kun': 'дн.',
  'soat': 'ч',
  'Jarima': 'Штраф',
  'Ishlagan kun': 'Отработано дней',
  'Ishlagan soat': 'Отработано часов',
  'Xodim': 'Сотрудник',
  'Hisob-kitob': 'Расчёт',
  'Ish haqi varaqasi': 'Платёжная ведомость',
  'Davr': 'Период',
  'Jami hisoblangan': 'Всего начислено',
  'Jami to\'lanadigan': 'Всего к выплате',
  'Yanvar': 'Январь',
  'Fevral': 'Февраль',
  'Mart': 'Март',
  'Aprel': 'Апрель',
  'May': 'Май',
  'Iyun': 'Июнь',
  'Iyul': 'Июль',
  'Avgust': 'Август',
  'Sentabr': 'Сентябрь',
  'Oktabr': 'Октябрь',
  'Noyabr': 'Ноябрь',
  'Dekabr': 'Декабрь',

  // ── Avans ──
  'Avans': 'Аванс',
  'Qoldiq': 'Остаток',
  'Avans qo\'shish': 'Добавить аванс',
  'Avanslar': 'Авансы',
  'Avans yo\'q': 'Авансов нет',
  'Sof maosh': 'Чистая зарплата',
  'Summa': 'Сумма',

  // ── To'lov / Kassa ──
  'To\'lov': 'Оплата',
  'Chegirma': 'Скидка',
  'Chegirma sababi': 'Причина скидки',
  'Karta': 'Карта',
  'Naqd': 'Наличные',
  'Qarz': 'Долг',
  'Qarzdor': 'Должник',
  'Mijoz ism-familiyasi': 'Имя и фамилия клиента',
  'Yakuniy': 'Итого',
  'Summa oshib ketdi': 'Сумма превышена',
  'Tugatish': 'Завершить',

  // ── Kassa (qo'shimcha) ──
  'Kassa': 'Касса',
  'Tushum': 'Приход',
  'Chiqim': 'Расход',
  'Tranzaksiyalar': 'Транзакции',
  'Qarzdorlar': 'Должники',
  'To\'lash': 'Оплатить',
  'Qarzni to\'lash': 'Оплата долга',
  'Tranzaksiya yo\'q': 'Нет транзакций',
  'Qarzdor yo\'q': 'Нет должников',
  'Yangi harakat': 'Новая операция',
  'to\'landi': 'оплачено',
  'Zakaz': 'Заказ',
  'Qo\'lda': 'Вручную',

  // ── Hisobot ──
  'Moliyaviy': 'Финансы',
  'Davomat': 'Посещаемость',
  'Eng ko\'p sotilgan': 'Самые продаваемые',

  // ── Oylik to'lash (Faza 3) ──
  'Oylik to\'lash': 'Выплатить зарплату',
  'Oylik berildi': 'Зарплата выдана',
  'To\'lovlar': 'Выплаты',
  'To\'lov yo\'q': 'Выплат нет',
  'To\'lov kuni (oyning kuni)': 'День выплаты (число месяца)',
  // ── Dashboard kun ──
  'Kun tanlash': 'Выбрать день',

  // ── Face ID qurilma ──
  'Qurilmaga qo\'shish (Face ID)': 'Добавить на устройство (Face ID)',
  'Avval Face ID raqamini kiriting!': 'Сначала введите номер Face ID!',
  'Qurilmaga yuborilmoqda...': 'Отправка на устройство...',

  // ── Oylik davri ──
  'Necha kunda oylik (kun)': 'Зарплата каждые N дней (дней)',
  '* Masalan: 30 = oylik, 10 = har 10 kunda': '* Например: 30 = ежемесячно, 10 = каждые 10 дней',
  'Oylik davri': 'Период зарплаты',
  'Har': 'Каждые',
  'oxirgisidan': 'с последней',

  // ── Jarima ──
  'Jarimalar': 'Штрафы',
  'Jarima yo\'q': 'Штрафов нет',
  'Sabab': 'Причина',

  // ── Bonus ──
  'Bonus': 'Бонус',
  'Bonuslar': 'Бонусы',
  'Bonus yo\'q': 'Бонусов нет',
  'aralash': 'смешанно',

  // ── Jarima override + manba ──
  'Kechikish jarimasi': 'Штраф за опоздание',
  'Avtomatik': 'Автоматически',
  'Yangi jarima': 'Новый штраф',
  '0 = to\'liq kechirish': '0 = полностью простить',
  'tahrirlangan': 'изменено',
  'Pul manbasi': 'Источник денег',
  'Kassadan': 'Из кассы',
  'Boshqa joydan': 'Из другого места',
  'Qayerdan': 'Откуда',
  'masalan: Direktor cho\'ntagidan': 'например: из кармана директора',
  'Kassadan pul yechilmaydi': 'Деньги из кассы не списываются',

  // -- Xarajat turlari --
  'Turlar': 'Типы',
  'Xarajat turlari': 'Типы расходов',
  'Tur nomini o\'zgartirish': 'Изменить название типа',
  'Tur nomi': 'Название типа',
  'Turni o\'chirish': 'Удалить тип',
  'Tur yo\'q': 'Нет типов',

  'Xarajat': 'Расход',

  'Sababsiz': 'Без причины',

  'Kassadan jami': 'Всего из кассы',
  'Boshqa manbadan': 'Из другого источника',

  // -- Stol shakli/zal --
  'Shakl': 'Форма',
  'To\'rtburchak': 'Прямоугольник',
  'Dumaloq': 'Круглый',
  'Xona: bosib kiring • ⋮ menyu (tahrir/o\'chirish) • suring': 'Зал: нажмите — войти • ⋮ меню (изменить/удалить) • тащите',
  'Stolni bosing — shakl, o\'lcham, o\'chirish': 'Нажмите на стол — форма, размер, удаление',

  // -- Kassa PDF --
  'Kassa hisoboti': 'Отчёт кассы',
  'Tushum (savdo)': 'Поступления (продажи)',
  'Jami savdo': 'Всего продаж',
  'Chiqim (harajat)': 'Расход',
  'Kassada bo\'lishi kerak': 'Должно быть в кассе',
  'Kartada': 'На карте',
  'Naqd (qo\'lda)': 'Наличные (в руках)',
  'Jami qoldiq': 'Итого остаток',
  'Kassir imzosi': 'Подпись кассира',
  'ELEKTRON': 'ЭЛЕКТРОННАЯ',
  // -- To'liq kassa hisoboti (PDF) --
  'Pul kiritish': 'Внести деньги',
  'Pul chiqarish': 'Изъять деньги',
  // --- Kunlik kuzat (somsa kabi) ---
  'Kunlik taomlar': 'Дневные блюда',
  'Ertalab "tayyorlandi" soniga kiriting — tugasa sotuv to\'xtaydi':
      'Утром введите «приготовлено» — когда закончится, продажа остановится',
  'Tayyor': 'Готово',
  'Sotildi': 'Продано',
  'Qoldi': 'Осталось',
  'kunlik kuzat YOQILDI (Bosh sahifada son kiriting)':
      'дневной учёт ВКЛЮЧЁН (введите кол-во на Главной)',
  'kunlik kuzat o\'chirildi': 'дневной учёт выключен',
  // --- Polufabrikat (P/F) ---
  'Polufabrikat': 'Полуфабрикат',
  'Polufabrikat qo\'shish': 'Добавить полуфабрикат',
  'P/F tanlang': 'Выберите полуфабрикат',
  'P/F yo\'q — avval kategoriyada "Polufabrikat qo\'shish" bilan yarating':
      'П/Ф нет — сначала создайте через "Добавить полуфабрикат" в категории',
  'Tayyorlash': 'Приготовить',
  'Qancha tayyorlandi? Xom masaliqlar retsept bo\'yicha skladdan ayriladi.':
      'Сколько приготовлено? Сырьё спишется со склада по рецепту.',
  'Qisqacha': 'Кратко',
  'To\'liq hisobot': 'Полный отчёт',
  'Hozirgi holat — savdo/karta/naqd/qoldiq': 'Текущее состояние — продажи/карта/наличные/остаток',
  'Harajat, ofitsant, taom, qarzdor — boshliqqa': 'Расходы, официанты, блюда, должники — руководителю',
  'To\'liq hisobot tayyorlanmoqda...': 'Готовится полный отчёт...',
  'To\'liq kassa hisoboti': 'Полный кассовый отчёт',
  '1. Tushum (kirim)': '1. Приход',
  '2. Harajatlar (kassadan)': '2. Расходы (из кассы)',
  'Nima uchun': 'На что',
  'Usul': 'Способ',
  'Harajat — karta': 'Расход — карта',
  'Harajat — naqd': 'Расход — наличные',
  '3. TOPSHIRILADIGAN (harajat ayrilgan)': '3. К СДАЧЕ (за вычетом расходов)',
  'JAMI TOPSHIRILADIGAN': 'ИТОГО К СДАЧЕ',
  'Float (kassada qoladi)': 'Float (остаётся в кассе)',
  'Qarz (olinmagan)': 'Долг (не получено)',
  '4. Ofitsantlar': '4. Официанты',
  'Taom': 'Блюдо',
  'Dona': 'Шт',
  'Boshqa taomlar (sotilgan)': 'Другие блюда (проданные)',
  'Ism': 'Имя',
  'Sana': 'Дата',
  'Umuman sotilmagan taomlar (0)': 'Совсем не проданные блюда (0)',
  'Hammasi sotilgan': 'Всё продано',
  'Boshliq imzosi': 'Подпись руководителя',

  // -- Kassa qulf --
  'Kassa himoyalangan': 'Касса защищена',
  'Davom etish uchun parolingizni kiriting': 'Введите пароль для продолжения',
  'Parolni kiriting': 'Введите пароль',
  'Parol noto\'g\'ri': 'Неверный пароль',
};
