-- Floor-plan: xonalar va stol joylashuvi (nisbiy koordinatalar 0.0..1.0)
CREATE TABLE IF NOT EXISTS rooms (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  pos_x DOUBLE PRECISION DEFAULT 0.1,
  pos_y DOUBLE PRECISION DEFAULT 0.1,
  width DOUBLE PRECISION DEFAULT 0.3,
  height DOUBLE PRECISION DEFAULT 0.3,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE tables ADD COLUMN IF NOT EXISTS room_id INTEGER REFERENCES rooms(id);
ALTER TABLE tables ADD COLUMN IF NOT EXISTS seats INTEGER DEFAULT 4;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS pos_x DOUBLE PRECISION DEFAULT 0.5;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS pos_y DOUBLE PRECISION DEFAULT 0.5;
