-- Ingredientlar narxlari - 241 ta

UPDATE ingredients SET price_per_unit = 30 WHERE name ILIKE '%Corona газированный 1л%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 206 WHERE name ILIKE '%Айсберг%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 220 WHERE name ILIKE '%Апельсин%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Баклажан%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 240 WHERE name ILIKE '%Бальзамический Соус%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 150 WHERE name ILIKE '%Банан%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 120 WHERE name ILIKE '%Батон для сухари (Гренки )%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 750 WHERE name ILIKE '%Бодоно мяса%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 3 WHERE name ILIKE '%Виноградный лист%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 180 WHERE name ILIKE '%Гарох (Нут)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Говяжий язык%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 250 WHERE name ILIKE '%Голен куриный ножки%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1200 WHERE name ILIKE '%Горчица%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 90 WHERE name ILIKE '%Гречка%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 150 WHERE name ILIKE '%Грибы шампиноны%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1700 WHERE name ILIKE '%Деми глазур%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 360 WHERE name ILIKE '%Дрож%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 200 WHERE name ILIKE '%Жыр говядина%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 400 WHERE name ILIKE '%Зажарка%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 400 WHERE name ILIKE '%Зажарка ТТК%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Зелень%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Зелень (Кинза свежая)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Зелень (Кинза)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Зелень (кинза свежая)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Зелень (кинза)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Зелень (укроп)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 600 WHERE name ILIKE '%Зира%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 150 WHERE name ILIKE '%Зыгыр масло%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 350 WHERE name ILIKE '%Имбир свежый%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 540 WHERE name ILIKE '%Кабачок%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1500 WHERE name ILIKE '%Казы%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 480 WHERE name ILIKE '%Каймак%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 160 WHERE name ILIKE '%Капуста Квашенная%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 200 WHERE name ILIKE '%Капуста красный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 150 WHERE name ILIKE '%Капуста обычный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 21 WHERE name ILIKE '%Картофель%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 190 WHERE name ILIKE '%Картофель по деревенсий%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 420 WHERE name ILIKE '%Картофель фри%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 190 WHERE name ILIKE '%КартофельШарик%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 420 WHERE name ILIKE '%Картошка%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 60 WHERE name ILIKE '%Картошка пюре%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 600 WHERE name ILIKE '%Катлеты (Фарш)П/Ф%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 110 WHERE name ILIKE '%Кетчуп%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 300 WHERE name ILIKE '%Кинза%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 450 WHERE name ILIKE '%Колбаса%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 450 WHERE name ILIKE '%Колбаса Пеперонни%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 300 WHERE name ILIKE '%Кориандр%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 600 WHERE name ILIKE '%Котлет%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 600 WHERE name ILIKE '%Котлет П/Ф%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 160 WHERE name ILIKE '%Котлет пф%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 120 WHERE name ILIKE '%Крахмал%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 430 WHERE name ILIKE '%Кукуруз консерванный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 270 WHERE name ILIKE '%Кунжут%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 700 WHERE name ILIKE '%Курдючный жир%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 700 WHERE name ILIKE '%Курдючный жыр баранина%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 50 WHERE name ILIKE '%Куриные крылышки%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 350 WHERE name ILIKE '%Куриный Филе%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 350 WHERE name ILIKE '%Куриный филе%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Лаваш%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 2000 WHERE name ILIKE '%Лавровый лист%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 270 WHERE name ILIKE '%Лапша фетучино%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 30 WHERE name ILIKE '%Лепешка%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 350 WHERE name ILIKE '%Лимон%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1200 WHERE name ILIKE '%Листя салата%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Лук зел%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Лук зел.%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Лук зеленый%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 200 WHERE name ILIKE '%Лук красный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 100 WHERE name ILIKE '%Лук репка%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 50 WHERE name ILIKE '%Лук репка (20% потер%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 50 WHERE name ILIKE '%Лук репчатый%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Майинез%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 300 WHERE name ILIKE '%Майонез%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Майыз%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 70 WHERE name ILIKE '%Макарон спирал (для бифстекс)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1050 WHERE name ILIKE '%Маракуйя пюре%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1000 WHERE name ILIKE '%Маслены%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 160 WHERE name ILIKE '%Масло Растительное%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 150 WHERE name ILIKE '%Масло раст.%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 150 WHERE name ILIKE '%Масло растительна%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Масло растительная%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 132 WHERE name ILIKE '%Масло растительный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 350 WHERE name ILIKE '%Масло сливочная%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 125 WHERE name ILIKE '%Молоко%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 120 WHERE name ILIKE '%Молоко Веселый молочник 2,5%%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 200 WHERE name ILIKE '%Морков красный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 100 WHERE name ILIKE '%Морковь%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 80 WHERE name ILIKE '%Морковь жел.%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 100 WHERE name ILIKE '%Морковь желтый%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 100 WHERE name ILIKE '%Морковь крас.%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 100 WHERE name ILIKE '%Морковь красный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 290 WHERE name ILIKE '%Морожено%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 290 WHERE name ILIKE '%Мороженое%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 73 WHERE name ILIKE '%Мука%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 850 WHERE name ILIKE '%Мяса говядина%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 700 WHERE name ILIKE '%Мясо Баранина (Быкын)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 700 WHERE name ILIKE '%Мясо Говядина%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 850 WHERE name ILIKE '%Мясо баранина%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 800 WHERE name ILIKE '%Мясо баранина (лахм )%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 850 WHERE name ILIKE '%Мясо говядина%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 700 WHERE name ILIKE '%Мясо говядина (быкын)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 800 WHERE name ILIKE '%Мясо говядина (лахм )%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 650 WHERE name ILIKE '%Мята%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 150 WHERE name ILIKE '%Мёд%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 140 WHERE name ILIKE '%Новот%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 420 WHERE name ILIKE '%Облипиховый сироп%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 160 WHERE name ILIKE '%Огурец%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 160 WHERE name ILIKE '%Огурец маринованые (Соленья)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 150 WHERE name ILIKE '%Огурец соленный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Огурцы%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 300 WHERE name ILIKE '%Оливковое масло%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 300 WHERE name ILIKE '%Оливковый масло%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 600 WHERE name ILIKE '%Орехи%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 200 WHERE name ILIKE '%Паприка сладкий%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 666 WHERE name ILIKE '%Пекинская капуста Басай (25% потеря%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 470 WHERE name ILIKE '%Пельмень%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 160 WHERE name ILIKE '%Перец Балгарский%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 250 WHERE name ILIKE '%Перец Красный острый (Чили)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Перец болгарский%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Перец болгарский зел%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Перец болгарский зел.%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Перец болгарский зеленый%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Перец болгарский кр%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Перец болгарский крас%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Перец болгарский крас.%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 300 WHERE name ILIKE '%Перец болгарский красный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Перец болгарский крачный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Перец стручковый (Калампир)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 250 WHERE name ILIKE '%Перец стручковый (калампир)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 150 WHERE name ILIKE '%Перец черный молотый%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Помидор%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 160 WHERE name ILIKE '%Помидор маринованный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 400 WHERE name ILIKE '%Помидор черри%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 300 WHERE name ILIKE '%Пурец черный молотый%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 70 WHERE name ILIKE '%Рамен%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 350 WHERE name ILIKE '%Рис лазер%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 250 WHERE name ILIKE '%Рис чайханский%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1200 WHERE name ILIKE '%Рукола%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1200 WHERE name ILIKE '%Руколла%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Салат Витаминка ТТК%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Салат витамин П/Ф%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Салат витамин ТТК%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Салат витаминка ТТК%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 85 WHERE name ILIKE '%Сахар%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 85 WHERE name ILIKE '%Сахар\ Нават%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 170 WHERE name ILIKE '%Сахарный пудра%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 100 WHERE name ILIKE '%Свекла%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 280 WHERE name ILIKE '%Сельдерей стебель%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1150 WHERE name ILIKE '%Семга%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1180 WHERE name ILIKE '%Семга Лосос рыба%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 480 WHERE name ILIKE '%Сироп блю Кюрасао%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 400 WHERE name ILIKE '%Сироп клубничный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 400 WHERE name ILIKE '%Сироп лайм%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 400 WHERE name ILIKE '%Сироп маракуйя%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 400 WHERE name ILIKE '%Сироп махито%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 430 WHERE name ILIKE '%Сливки 1л (10% петеря за литр)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 420 WHERE name ILIKE '%Сливки 1л (10-20% )%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 420 WHERE name ILIKE '%Сливки 1л 10-20%%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 150 WHERE name ILIKE '%Сметано (700гр/шт)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 170 WHERE name ILIKE '%Соевый Соус%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 180 WHERE name ILIKE '%Соевый соус%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 160 WHERE name ILIKE '%Сок лимона соус%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 100 WHERE name ILIKE '%Сок лимона соус (7% потеря%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 300 WHERE name ILIKE '%Соленый огурцы ПФ (маринов.)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 25 WHERE name ILIKE '%Соль%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 17 WHERE name ILIKE '%Соус Грузинская аджика%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 350 WHERE name ILIKE '%Соус Чимган%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 340 WHERE name ILIKE '%Соус цезарь П/Ф%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 450 WHERE name ILIKE '%Соус чили сладкий%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 700 WHERE name ILIKE '%Стейк Томогавк%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 700 WHERE name ILIKE '%Стейк из говядина%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 350 WHERE name ILIKE '%Сыр Моцарела%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 470 WHERE name ILIKE '%Сыр Чечиль%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 470 WHERE name ILIKE '%Сыр моцарелла%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1000 WHERE name ILIKE '%Сыр пармезан%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1000 WHERE name ILIKE '%Сыр пармизан%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 400 WHERE name ILIKE '%Тархун сироп%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 450 WHERE name ILIKE '%Терияки соус%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 70 WHERE name ILIKE '%Теста 250гр%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 28 WHERE name ILIKE '%Теста 400гр%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 45 WHERE name ILIKE '%Теста 60гр%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 50 WHERE name ILIKE '%Теста ТТК%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 35 WHERE name ILIKE '%Теста лагман ТТК%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 165 WHERE name ILIKE '%Томатная паста%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 180 WHERE name ILIKE '%Томатный паста%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 20 WHERE name ILIKE '%Уголь%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 130 WHERE name ILIKE '%Уксус%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 125 WHERE name ILIKE '%Уксус 9%%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 600 WHERE name ILIKE '%Фарш (Катлет П/Ф)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 518 WHERE name ILIKE '%Фарш (Катлеты П/Ф)%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 396 WHERE name ILIKE '%Фарш хинкали П/Ф%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 180 WHERE name ILIKE '%Фасоль Маринованный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 800 WHERE name ILIKE '%Фетакса%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1100 WHERE name ILIKE '%Филе курица%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 540 WHERE name ILIKE '%Хлеб%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1200 WHERE name ILIKE '%Хмели-сунели приправа%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 5 WHERE name ILIKE '%Чай Фруктовый пакети%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 827 WHERE name ILIKE '%Чай черный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 700 WHERE name ILIKE '%Чарви баранина%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 850 WHERE name ILIKE '%Черный перец%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1000 WHERE name ILIKE '%Черный перец молотый%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Чеснок%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Чеснок Зеленый%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 550 WHERE name ILIKE '%Шампиньен%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 260 WHERE name ILIKE '%Шампиньён%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 100 WHERE name ILIKE '%Яблоко%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%Язык говяжий%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 11 WHERE name ILIKE '%Яйцо%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 6 WHERE name ILIKE '%Яйцо бедана%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 6 WHERE name ILIKE '%Яйцо перепелиный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 532 WHERE name ILIKE '%ананас%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 200 WHERE name ILIKE '%банан%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1000 WHERE name ILIKE '%ванилин%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 8.21 WHERE name ILIKE '%вафли%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 250 WHERE name ILIKE '%говяжий жыр%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 200 WHERE name ILIKE '%кетчуп%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 320 WHERE name ILIKE '%киви%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 1000 WHERE name ILIKE '%клубника%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%кореандр%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%кости ковядина%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 350 WHERE name ILIKE '%курин филе%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 160 WHERE name ILIKE '%куринный котлет%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 50 WHERE name ILIKE '%лук репч%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 132 WHERE name ILIKE '%масло растительный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 55 WHERE name ILIKE '%молоко%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 150 WHERE name ILIKE '%паприка сладкая%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 250 WHERE name ILIKE '%перец черный молотый%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 120 WHERE name ILIKE '%перец чили%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 500 WHERE name ILIKE '%петрушка%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 400 WHERE name ILIKE '%разрыхлитель%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 300 WHERE name ILIKE '%салат микс%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 85 WHERE name ILIKE '%сахар%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 200 WHERE name ILIKE '%соль%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 206 WHERE name ILIKE '%соус бургер%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 170 WHERE name ILIKE '%соус сладкий%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 420 WHERE name ILIKE '%соус чесночный%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 60 WHERE name ILIKE '%хлеб%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 150 WHERE name ILIKE '%хлеб багет%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 150 WHERE name ILIKE '%чеснок%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 850 WHERE name ILIKE '%шоколад%' AND price_per_unit = 0;
UPDATE ingredients SET price_per_unit = 11 WHERE name ILIKE '%яйцо%' AND price_per_unit = 0;